print("..123456789012..00..123456789012..00..123456789012..00..")
print("     SSSSSSSS       HH        HH      XXX      XXX      ")
print("    SSS   SSSS      HH        HH       XXX    XXX       ")
print("    SSS             HH        HH        XXX  XXX        ")
print("     SSS            HH        HH         XX  XX         ")
print("      SSS           HHHHHHHHHHHH          XXXX          ")
print("        SSS         HHHHHHHHHHHH          XXXX          ")
print("         SSS        HH        HH         XX  XX         ")
print("          SSS       HH        HH        XXX  XXX        ")
print("  SSSS    SSS   ..  HH        HH  ..   XXX    XXX   ..  ")
print("    SSSSSSSS    ..  HH        HH  ..  XXX      XXX  ..  ")
